spring:
  application:
    name: alert-service
  config:
    import: optional:configserver:http://localhost:8888

  mail:
    host: smtp.gmail.com
    port: 587
    username: youssefmennani1996@gmail.com
    password: iqsp ylvi qpkn xfpo
    properties:
      mail:
        smtp:
          auth: true
          trust: "*"
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8