#server:
#  port: 8222
#
#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}
#
#spring:
#
#
#  cloud:
#    gateway:
##      globalcors:
##        corsConfigurations:
##          '[/**]':
##            allowedOrigins:
##              - "*"  # Specify the frontend address explicitly
##            allowedHeaders:
##              - "*"
##            allowedMethods:
##              - GET
##              - POST
##              - PUT
##              - DELETE
##            allowCredentials: true  # If cookies or auth headers are needed
#
#      discovery:
#        locator:
#          enabled: true
#
#      routes:
#        - id: vehicle-service
#          uri: lb:http://VEHICLE-SERVICE
#          predicates:
#            - Path=/api/v1/vehicles/**
#        - id: tracker-service
#          uri: lb:http://TRACKER-SERVICE
#          predicates:
#            - Path=/api/v1/trackers/**
#        - id: driver-service
#          uri: lb:http://DRIVER-SERVICE
#          predicates:
#            - Path=/api/v1/drivers/**
#        - id: position-service
#          uri: lb:http://POSITION-SERVICE
#          predicates:
#            - Path=/api/v1/positions/**
#        - id: minio-service
#          uri: lb:http://MINIO-SERVICE
#          predicates:
#            - Path=/minio/**
#        - id: user-service
#          uri: lb:http://USER-SERVICE
#          predicates:
#            - Path=/api/userextras/**
#        - id: subscription-service
#          uri: lb:http://SUBSCRIPTION-SERVICE
#          predicates:
#            - Path=/api/v1/{segment:subscription|payment}/**
##            - Path=/api/v1/subscription/**
#jwt:
#  auth:
#    converter:
#      resource-id: fleet-management-system
#      principal-attribute: preferred_username
#
#
#
#app:
#  cors:
#    allowed-origins: "*"
#
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty: DEBUG
#    org.springframework.web: DEBUG

server:
  port: 8222

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  # Recommended for consistency

      routes:
        - id: vehicle-service
          uri: lb://VEHICLE-SERVICE
          predicates:
            - Path=/api/v1/vehicles/**
#          filters:
#            - RewritePath=/api/v1/vehicles/(?<remaining>.*), /$\{remaining}

        - id: tracker-service
          uri: lb://TRACKER-SERVICE
          predicates:
            - Path=/api/v1/trackers/**
#          filters:
#            - RewritePath=/api/v1/trackers/(?<remaining>.*), /$\{remaining}

        - id: driver-service
          uri: lb://DRIVER-SERVICE
          predicates:
            - Path=/api/v1/drivers/**
#          filters:
#            - RewritePath=/api/v1/drivers/(?<remaining>.*), /$\{remaining}

        - id: position-service
          uri: lb://POSITION-SERVICE
          predicates:
            - Path=/api/v1/positions/**
#          filters:
#            - RewritePath=/api/v1/positions/(?<remaining>.*), /$\{remaining}

        - id: minio-service
          uri: lb://MINIO-SERVICE
          predicates:
            - Path=/minio/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/userextras/**
#          filters:
#            - RewritePath=/api/userextras/(?<remaining>.*), /$\{remaining}

        - id: subscription-service
          uri: lb://SUBSCRIPTION-SERVICE
          predicates:
            - Path=/api/v1/{segment:subscription|payment}/**
#          filters:
#            - RewritePath=/api/v1/(?<segment>subscription|payment)/(?<remaining>.*), /$\{remaining}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    org.springframework.web: DEBUG