spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/fleet-management-system
          jwk-set-uri: http://localhost:9090/realms/fleet-management-system/protocol/openid-connect/certs
          ssl-verification-disabled: true # <== attention, option non standard