spring:
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: https://45.10.162.39:8443/realms/fleet-management-system
          jwk-set-uri: https://45.10.162.39:8443/realms/fleet-management-system/protocol/openid-connect/certs

  data:
    mongodb:
      uri: mongodb://45.10.162.39:27017/GeoTrackDB # injected from environment

app:
  cors:
    allowed-origins:
      - "*"

logging:
  level:
    org.springframework.security: INFO
