spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/fleet-management-system
          jwk-set-uri: http://localhost:9090/realms/fleet-management-system/protocol/openid-connect/certs


management:
  endpoints:
    web:
      exposure:
        include: "*"