#spring.application.name=subscription-service
spring:
  application:
    name: subscription-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}

  profiles:
    active: prod  # or use an environment variable in Docker/CI