spring:
  application:
    name: user-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}

  profiles:
    active: prod  # or use an environment variable in Docker/CI

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

#
#        | Environment | What to set                              | What config gets loaded |
#        | ----------- | ---------------------------------------- | ----------------------- |
#        | Local dev   | `SPRING_PROFILES_ACTIVE=dev` (default)   | `user-service-dev.yml`  |
#        | Production  | `SPRING_PROFILES_ACTIVE=prod` + env vars | `user-service-prod.yml` |

#keycloak:
#  auth-server-url: http://localhost:9090/realms/fleet-management-system
#  realm: fleet-management-system
#  client-id: listener-client
#  client-secret: NIqu6THXwIVhiIRhUQjlblDUkXRVYzUu
#  grant-type: client_credentials
#  public-client: false
#  use-resource-role-mappings: true
#  bearer-only: true
#  security-constraints:
#    - auth-roles:
#        - "user"
#      security-roles:
#        - "admin"
